[build]
  publish = "."

[[redirects]]
  from = "https://www.play-it-straight.com/*"
  to = "https://play-it-straight.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/gallery"
  to = "/productions"
  status = 301

[[redirects]]
  from = "/gallery.html"
  to = "/productions.html"
  status = 301

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
